name = "MyStatsPackage"
uuid = "138fe3b7-58aa-40c1-bc81-1a701a9609ae"
authors = ["emanuel-kopp <emanuel.kopp@outlook.com>"]
version = "0.1.0"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
Example = "0.5.2"
ProgressMeter = "1.2"
